{% set name = "dicom-anonymizer" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dicom_anonymizer-{{ version }}.tar.gz
  sha256: 2cf2e6bf5c412163a2ab74e77ae917a1c7cffb9ab6dc730690f1862182547216

build:
  entry_points:
    - dicom-anonymizer = dicomanonymizer.anonymizer:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydicom
    - python >={{ python_min }}
    - tqdm

test:
  imports:
    - dicomanonymizer
  commands:
    - pip check
    - dicom-anonymizer --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/KitwareMedical/dicom-anonymizer
  summary: Program to anonymize dicom files with default and custom rules
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
