{% set name = "dicom-anonymizer" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dicom_anonymizer-{{ version }}.tar.gz
  sha256: 2318a8c06e7f655d6d7920471a60a0369a05f9079dfdff8875274b0cbd3756a5

build:
  entry_points:
    - dicom-anonymizer = dicomanonymizer.anonymizer:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pydicom
    - python >=3.6
    - tqdm

test:
  imports:
    - dicomanonymizer
  commands:
    - pip check
    - dicom-anonymizer --help
  requires:
    - pip

about:
  home: https://github.com/KitwareMedical/dicom-anonymizer
  summary: Program to anonymize dicom files with default and custom rules
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
