{% set name = "dicom-anonymizer" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dicom_anonymizer-{{ version }}.tar.gz
  sha256: 101ec37e6dc51ba1b2438b14adb569efde23830f6fe5fbae09f225963664b420

build:
  entry_points:
    - dicom-anonymizer = dicomanonymizer.anonymizer:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pydicom
    - python >=3.6
    - tqdm

test:
  imports:
    - dicomanonymizer
  commands:
    - pip check
    - dicom-anonymizer --help
  requires:
    - pip

about:
  home: https://github.com/KitwareMedical/dicom-anonymizer
  summary: Program to anonymize dicom files with default and custom rules
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
